#!/bin/bash
 set -x
# MASTER=hongqi@192.168.99.110
# scp ${MASTER}:~/.kube/config .
# export KUBECONFIG=$(pwd)/config

 image=wavecloud/nginx-std
 port=8081
 app=nginx
 docker build -f Dockerfile -t $image  .

 echo "push and remove docker images"
 docker login -uzhanghongqi -ppass
 docker push $image

 kubectl get pods

 kubectl delete deploy $app
 kubectl delete svc $app

 kubectl create deployment $app --image=$image --port=$port
 sleep 10
 kubectl expose deployment $app --target-port=$port --type=NodePort
 sleep 5
 kubectl port-forward svc/nginx  $port:$port &
 sleep 5

 if curl localhost:$port | grep 'Welcome HONGQI' ; then
    echo "verify successfully"
 else
    echo "ERROR: verify failure"
    exit 1;
 fi
 pid=`ps -ax|grep port-forward | awk 'NR==1{print $1}'`
 kill -9 $pid
