#!/bin/bash
 source ~/.rc
 set -x
 company=wavecloud
 port=8089
 app=myweb-app
 image=${company}/${app}
 set +x
 docker login -uzhanghongqi -p${dockerps}
 set -x
 docker build -f Dockerfile_adv -t $image  . --build-arg port=$port # override argument
 docker push $image

 docker rm -f $app
 docker image rm $image
 docker run --name $app -p $port:$port -d \
                        -e PORT=$port -v `pwd`:/tmp  \
                        $image  # override PORT

 echo "wait a whole"
 sleep 10

 echo "verify docker"
 if curl localhost:$port | grep 'Welcome to Hongqi Website' ; then
    echo "verify successfully"
 else
    echo "ERROR: verify failure"
    exit 1;
 fi

 echo "clean docker "
 docker rm -f $app
